const express = require('express')
const app = express()
const port = 5003
const bodyParser = require('body-parser')
var morgan = require('morgan')
var cors = require('cors')
var Prefix = require('./routes/prefix')
var Province = require('./routes/province')
var District = require('./routes/district')
var SubDistrict = require('./routes/subdistrict')
var Users = require('./routes/users')
var Owners = require('./routes/owner')
var TypeCategories = require('./routes/typecategories')
var Types = require('./routes/types')
var Company = require('./routes/company')
var RequestType = require('./routes/requesttype')
var RequestLicense = require('./routes/requestlicense')

app.use(cors())
app.use(morgan('tiny'))
app.use(express.static('assets'))
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())

Prefix(app)
Province(app)
District(app)
SubDistrict(app)
Users(app)
Owners(app)
TypeCategories(app)
Types(app)
Company(app)
RequestType(app)
RequestLicense(app)

app.listen(port, () => console.log(`Example app listening on port ${port}!`))