const express = require('express')
const app = express()
const port = 5003
const bodyParser = require('body-parser')
// var history = require('connect-history-api-fallback');
var morgan = require('morgan')
var cors = require('cors')
var Prefix = require('./routes/prefix')
var Boss = require('./routes/boss')
var Province = require('./routes/province')
var District = require('./routes/district')
var SubDistrict = require('./routes/subdistrict')
var Users = require('./routes/users')
var Owners = require('./routes/owner')
var TypeCategories = require('./routes/typecategories')
var Types = require('./routes/types')
var LicenseFee = require('./routes/licensefee')
var Company = require('./routes/company')
var RequestLicense = require('./routes/requestlicense')
var Investigation = require('./routes/investigation')
var InvestigationGeneral = require('./routes/investigationgeneral')
var InvestigationEnvironment = require('./routes/investigationenvironment')
var InvestigationSummary = require('./routes/investigationsummary')
var CompanyLicense = require('./routes/companylicense')

app.use(cors())
// app.use(history())
app.use(morgan('tiny'))
app.use(express.static('assets'))
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())

Prefix(app)
Boss(app)
Province(app)
District(app)
SubDistrict(app)
Users(app)
Owners(app)
TypeCategories(app)
Types(app)
LicenseFee(app)
Company(app)
RequestLicense(app)
Investigation(app)
InvestigationGeneral(app)
InvestigationEnvironment(app)
InvestigationSummary(app)
CompanyLicense(app)

app.listen(port, () => console.log(`Example app listening on port ${port}!`))